apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase-poc
  namespace: metabase-poc
spec:
  selector:
    matchLabels:
      app: metabase
  replicas: 1
  template:
    metadata:
      labels:
        app: metabase
    spec:
      serviceAccountName: metabase-sa
      containers:
      - name: metabase
        image: metabase/metabase
        ports:
        - containerPort: 3000
