apiVersion: v1
kind: Service
metadata:
  name: metabase-service
  namespace: metabase-poc
  labels:
    app: metabase
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: metabase-port
  selector:
    app: metabase
